name: CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Étape 1 : Cloner le dépôt
    - name: Checkout code
      uses: actions/checkout@v2

    # Étape 2 : Configurer Python
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    # Étape 3 : Connexion à Azure
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    # Étape 4 : Préparer l'application pour le déploiement
    - name: Zip application files
      run: |
        zip -r app.zip .

    # Étape 5 : Déployer sur Azure Web App existante
    - name: Deploy to Azure Web App
      run: |
        az webapp deployment source config-zip \
          --resource-group DevOpsM1 \
          --name health-calculator-serviceJo \
          --src app.zip