name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Étape 1 : Cloner le dépôt
    - name: Checkout code
      uses: actions/checkout@v2

    # Étape 2 : Configurer Python
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    # Étape 3 : Installer les dépendances
    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    # Étape 4 : Exécuter les tests
    - name: Run tests
      run: |
        python -m unittest discover