name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Étape 1 : Cloner le dépôt
      - name: Checkout code
        uses: actions/checkout@v2

      # Étape 2 : Configurer Docker
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Étape 3 : Construire l'image Docker
      - name: Build Docker image
        run: |
          docker build -t health-calculator .

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      # Étape 1 : Cloner le dépôt
      - name: Checkout code
        uses: actions/checkout@v2

      # Étape 2 : Connexion à Azure
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Étape 3 : Pousser l'image Docker sur Azure Container Registry (ACR)
      - name: Push Docker image to ACR
        run: |
          docker tag health-calculator healthcalcacr.azurecr.io/health-calculator:v1
          docker push healthcalcacr.azurecr.io/health-calculator:v1

      # Étape 4 : Déployer l'image Docker sur Azure Web App
      - name: Deploy to Azure Web App
        run: |
          az webapp config container set \
            --name health-calculator-serviceJo \
            --resource-group DevOpsM1 \
            --docker-custom-image-name healthcalcacr.azurecr.io/health-calculator:v1 \
            --docker-registry-server-url https://healthcalcacr.azurecr.io

      # Étape 5 : Vérifier le déploiement
      - name: Verify app deployment
        run: |
          sleep 10 # Attendre 10 secondes pour que l'app se déploie
          curl -f https://health-calculator-serviceJo.azurewebsites.net || exit 1
